#cloud-config
ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKlZY0GrmLS6WE1mjB32kQExU6PHZrIlkcoWBNG7XTZx
rancher:
  repositories:
    datacrypt:
      url: https://raw.githubusercontent.com/300481/datacrypt/master
    shield:
      url: https://raw.githubusercontent.com/300481/shield/master
  services_include:
    datacrypt: true
    shield: true
  ssh:
    port: 65002
  environment:
    SSH_PORT: 65002
    CRYPT_KEY_URL: https://www.googleapis.com/storage/v1/b/files3004/o/keyfile?alt=media

